name: Examples

on:
  push:
    branches: [ testing ]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo "Hello World...."

      - name: Print again
        run: echo "Hello World again...."
